mitkFunctionAddExternalProject(NAME Poco ON COMPONENTS Foundation Net Util XML Zip)
mitkFunctionAddExternalProject(NAME CppUnit ON ADVANCED DOC "Use CppUnit for unit tests")
#mitkFunctionAddExternalProject(NAME Boost ON NO_CACHE)
mitkFunctionAddExternalProject(NAME ZLIB OFF ADVANCED)
mitkFunctionAddExternalProject(NAME lz4 ON ADVANCED)
mitkFunctionAddExternalProject(NAME OpenMesh OFF)
mitkFunctionAddExternalProject(NAME CTK ON DEPENDS Qt5 DOC "Use CTK in MITK")
mitkFunctionAddExternalProject(NAME nlohmann_json ON ADVANCED)
mitkFunctionAddExternalProject(NAME ITKCommon ON ADVANCED DEPENDS VNL)
mitkFunctionAddExternalProject(NAME CppMicroServices ON DEPENDS nlohmann_json)
mitkFunctionAddExternalProject(NAME KWSys ON ADVANCED)
mitkFunctionAddExternalProject(NAME VNL ON ADVANCED)

if(MITK_USE_Qt5)
 mitkFunctionAddExternalProject(NAME Qwt ON ADVANCED DEPENDS Qt5)
endif()

if(UNIX AND NOT APPLE)
  mitkFunctionAddExternalProject(NAME PCRE OFF ADVANCED NO_PACKAGE)
  mitkFunctionAddExternalProject(NAME SWIG OFF ADVANCED NO_PACKAGE DEPENDS PCRE)
elseif(WIN32)
  mitkFunctionAddExternalProject(NAME SWIG OFF ADVANCED NO_PACKAGE)
endif()
